INSERT INTO USER (USER_ID, USERNAME, PASSWORD, NAME) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin');
INSERT INTO USER (USER_ID, USERNAME, PASSWORD, NAME) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user');

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('STUDENT');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('EDUCATOR');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ADMIN');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'STUDENT');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (2, 'EDUCATOR');