-- http://sqlines.com/mysql/set_foreign_key_checks
-- https://junghyungil.tistory.com/85
-- https://woowacourse.github.io/javable/post/2020-09-15-test-isolation/
SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE AUTHORITY;
TRUNCATE TABLE COMMENT;
TRUNCATE TABLE DICTIONARY;
TRUNCATE TABLE DICTIONARY_TAG_LIST;
TRUNCATE TABLE IMAGE;
TRUNCATE TABLE LECTURE;
TRUNCATE TABLE LECTURE_TAG_LIST;
TRUNCATE TABLE POST;
TRUNCATE TABLE USER;
TRUNCATE TABLE USER_AUTHORITY;
TRUNCATE TABLE USER_COMMENT_LIKE_ID_LIST;
TRUNCATE TABLE USER_COMMENT_LIST;
TRUNCATE TABLE USER_POST_LIKE_ID_LIST;
TRUNCATE TABLE USER_POST_LIST;

INSERT INTO AUTHORITY (AUTHORITY_NAME)
values ('ROLE_STUDENT');
INSERT INTO AUTHORITY (AUTHORITY_NAME)
values ('ROLE_EDUCATOR');
INSERT INTO AUTHORITY (AUTHORITY_NAME)
values ('ROLE_ADMIN');

SET FOREIGN_KEY_CHECKS = 1;